import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 12,
    paddingBottom: 12,
    fontSize: 7,
    fontFamily: "Times-Roman",
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    borderBottom: "2 solid #dc2626",
    paddingBottom: 8,
  },
  headerLeft: {
    width: "50%",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  logo: {
    width: 40,
    height: 40,
    marginRight: 8,
    objectFit: "contain",
  },
  companyName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#374151",
    fontFamily: "Times-Bold",
  },
  addressColumn: {
    fontSize: 7,
    color: "#374151",
    lineHeight: 1.4,
    marginBottom: 1,
  },
  slogan: {
    fontSize: 9,
    color: "#6b7280",
    fontStyle: "italic",
    marginTop: 5,
  },
  headerRight: {
    width: "45%",
    alignItems: "flex-end",
  },
  reportTitle: {
    fontSize: 11,
    fontWeight: "medium",
    color: "#111827",
    marginBottom: 6,
    fontFamily: "Times-Bold",
  },
  infoRow: {
    fontSize: 7,
    color: "#374151",
    marginBottom: 2,
    textAlign: "right",
  },
  generalInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
    padding: 8,
    backgroundColor: "#f9fafb",
    borderRadius: 3,
  },
  generalInfoLeft: {
    width: "30%",
  },
  generalInfoCenter: {
    width: "35%",
  },
  generalInfoRight: {
    width: "30%",
  },
  growerBox: {
    padding: 6,
    backgroundColor: "#ffffff",
    border: "1 solid #e5e7eb",
    borderRadius: 2,
    marginTop: 4,
  },
  growerText: {
    fontSize: 8,
    color: "#111827",
  },
  labelText: {
    fontSize: 8,
    color: "#6b7280",
    marginBottom: 3,
  },
  valueText: {
    fontSize: 9,
    color: "#111827",
    fontWeight: "bold",
  },
  tablesContainer: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    alignItems: "flex-start",
  },
  table: {
    border: "1 solid #000000",
    borderRadius: 10,
    overflow: "hidden",
    width: "100%",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderBottom: "2 solid #000000",
    paddingVertical: 4,
    paddingHorizontal: 2,
    alignItems: "flex-start",
  },
  headerCell: {
    fontSize: 5,
    fontWeight: "bold",
    color: "#000000",
    fontFamily: "Times-Bold",
    textAlign: "center",
  },
  testCell: {
    width: "14%",
    paddingRight: 2,
    paddingLeft: 2,
    borderRight: "1 solid #000000",
  },
  methodCell: {
    width: "11%",
    textAlign: "center",
    paddingHorizontal: 1,
    borderRight: "1 solid #000000",
  },
  resultsCell: {
    width: "10%",
    textAlign: "center",
    paddingHorizontal: 1,
    borderRight: "1 solid #000000",
  },
  rangeCell: {
    width: "50%",
    paddingLeft: 2,
    paddingRight: 1,
    flexDirection: "column",
    borderRight: "1 solid #000000",
  },
  cecCell: {
    width: "15%",
    textAlign: "center",
    paddingHorizontal: 1,
  },
  cecCellData: {
    width: "15%",
    textAlign: "center",
    paddingHorizontal: 1,
    backgroundColor: "#ffffff",
    alignSelf: "stretch",
    justifyContent: "center",
  },
  additionalCell: {
    width: "8%",
    textAlign: "center",
    paddingHorizontal: 1,
    borderRight: "1 solid #000000",
    justifyContent: "center",
    alignItems: "center",
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1 solid #d1d5db",
    paddingVertical: 3,
    paddingHorizontal: 2,
    alignItems: "center",
    minHeight: 24,
  },
  testName: {
    fontSize: 5,
    color: "#000000",
    fontWeight: "bold",
    fontFamily: "Times-Bold",
  },
  methodText: {
    fontSize: 4.5,
    color: "#000000",
    textAlign: "center",
    fontFamily: "Times-Roman",
  },
  resultText: {
    fontSize: 5,
    color: "#000000",
    textAlign: "center",
    fontWeight: "bold",
    fontFamily: "Times-Bold",
  },
  ratingHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    paddingHorizontal: 1,
    flexWrap: "wrap",
  },
  ratingLabel: {
    fontSize: 4.5,
    color: "#000000",
    fontWeight: "bold",
    fontFamily: "Times-Bold",
  },
  barContainer: {
    height: 10,
    position: "relative",
    backgroundColor: "#ffffff",
    borderRadius: 1,
    overflow: "hidden",
    border: "0.5 solid #000000",
    width: "100%",
    marginTop: 1,
  },
  barSegment: {
    height: "100%",
    position: "absolute",
    top: 0,
  },
  barIndicator: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1.5,
    backgroundColor: "#000000",
    zIndex: 10,
  },
  ratingText: {
    fontSize: 4.5,
    color: "#000000",
    fontWeight: "bold",
    fontFamily: "Times-Bold",
    textAlign: "center",
  },
  cecText: {
    fontSize: 5,
    color: "#000000",
    textAlign: "center",
    fontFamily: "Times-Roman",
  },
  section: {
    marginTop: 15,
    padding: 8,
    backgroundColor: "#f9fafb",
    borderRadius: 3,
    border: "1 solid #e5e7eb",
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 5,
    fontFamily: "Times-Bold",
  },
  sectionText: {
    fontSize: 9,
    color: "#374151",
    marginBottom: 5,
  },
  cecTable: {
    width: "30%",
    border: "1 solid #000000",
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#ffffff",
  },
  cecTableHeader: {
    backgroundColor: "#f3f4f6",
    padding: 6,
    borderBottom: "1 solid #000000",
  },
  cecTableTitle: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#111827",
    fontFamily: "Times-Bold",
    marginBottom: 2,
  },
  cecTableSubtitle: {
    fontSize: 6.5,
    color: "#374151",
    fontFamily: "Times-Roman",
  },
  cecTableContent: {
    padding: 0,
  },
  cecTableRow: {
    flexDirection: "row",
    borderBottom: "1 solid #d1d5db",
    paddingVertical: 3,
    paddingHorizontal: 5,
    backgroundColor: "#ffffff",
    minHeight: 24,
  },
  cecTableHeaderRow: {
    backgroundColor: "#ffffff",
    borderBottom: "1 solid #000000",
  },
  cecTableCell: {
    fontSize: 6.5,
    color: "#111827",
    fontFamily: "Times-Roman",
    flex: 1,
    textAlign: "left",
  },
  cecTableCellHeader: {
    fontSize: 6.5,
    color: "#111827",
    fontWeight: "bold",
    fontFamily: "Times-Bold",
    flex: 1,
    textAlign: "left",
  },
  saturationTable: {
    marginTop: 8,
    border: "1 solid #d1d5db",
  },
  saturationRow: {
    flexDirection: "row",
    borderBottom: "1 solid #e5e7eb",
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  saturationCell: {
    fontSize: 8,
    color: "#111827",
    width: "20%",
  },
  recommendationCard: {
    marginTop: 5,
    marginBottom: 5,
    padding: 7,
    backgroundColor: "#ffffff",
    borderRadius: 4,
    border: "1 solid #e5e7eb",
    borderLeft: "3 solid #3b82f6",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
  },
  recommendationHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  recommendationIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#3b82f6",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
  },
  recommendationIconText: {
    color: "#ffffff",
    fontSize: 6,
    fontWeight: "bold",
    fontFamily: "Times-Bold",
  },
  recommendationTitle: {
    fontSize: 7,
    fontWeight: "bold",
    color: "#111827",
    fontFamily: "Times-Bold",
    flex: 1,
  },
  recommendationContent: {
    paddingLeft: 26,
  },
  recommendationText: {
    fontSize: 6,
    color: "#374151",
    lineHeight: 1.4,
    fontFamily: "Times-Roman",
  },
  recommendationBold: {
    fontWeight: "bold",
    fontFamily: "Times-Bold",
    color: "#111827",
  },
  footer: {
    position: "absolute",
    bottom: 15,
    left: 30,
    right: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: "#9ca3af",
    borderTop: "1 solid #e5e7eb",
    paddingTop: 8,
  },
  footerLeft: {
    width: "50%",
  },
  footerLogoContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  footerLogo: {
    width: 30,
    height: 30,
    objectFit: "contain",
  },
  footerCompanyName: {
    fontSize: 7,
    fontWeight: "bold",
    color: "#dc2626",
    fontFamily: "Times-Bold",
    marginBottom: 2,
  },
  footerText: {
    fontSize: 6,
    color: "#6b7280",
    fontFamily: "Times-Roman",
    marginBottom: 2,
  },
  footerRight: {
    width: "50%",
    textAlign: "right",
    justifyContent: "flex-end",
  },
});