#!/bin/bash

# Complete test record with all fields filled
curl -X POST http://localhost:3001/api/records \
  -H "Content-Type: application/json" \
  -d '{
  "name": "Rajesh Kumar",
  "parentage": "Ram Kumar",
  "address": "Village: Sukhdev Nagar, Post: Mandi",
  "district": "Shimla",
  "pinCode": "171001",
  "phoneNo": "9876543210",
  "adharNo": "1234 5678 9012",
  "khasraNo": "123/45/67",
  "latitude": "31.1048",
  "longitude": "77.1734",
  "location": "Sukhdev Nagar",
  "city": "Shimla",
  "stateVal": "Himachal Pradesh",
  "crop": "apple",
  "cropOther": null,
  "variety": null,
  "plantationType": "high-density",
  "plantationTypeOther": null,
  "age": 5,
  "noTrees": 200,
  "area": 2.5,
  "noOfSamples": 3,
  "soilDepth": "0-30 cm",
  "soilType": "loamy",
  "soilTypeOther": null,
  "drainage": "well-drained",
  "drainageOther": null,
  "irrigationMethod": "drip",
  "irrigationMethodOther": null,
  "paramPh": true,
  "paramDl": true,
  "paramCl": true,
  "parameterPrice": 150,
  "paymentStatus": "paid",
  "paymentDate": "2024-01-15T10:30:00.000Z",
  "paidAmount": 150,
  "ph": "6.5",
  "organicCarbon": "0.85",
  "nitrogen": "350",
  "phosphorus": "18",
  "potassium": "250",
  "calcium": "1200",
  "magnesium": "350",
  "nitrogenRating": "Medium",
  "phosphorusRating": "Optimum",
  "potassiumRating": "Optimum",
  "testResults": [
    {
      "id": "test-1705312200000-abc123",
      "ph": "6.5",
      "bufferPh": "7.2",
      "organicCarbon": "0.85",
      "nitrogen": "350",
      "phosphorus": "18",
      "potassium": "250",
      "calcium": "1200",
      "magnesium": "350",
      "sulfur": "15",
      "iron": "5.5",
      "manganese": "12",
      "zinc": "1.8",
      "copper": "1.2",
      "boron": "0.6",
      "molybdenum": "0.15",
      "chlorine": "35",
      "nickel": "0.5",
      "sodium": "80",
      "electricalConductivity": "1.5",
      "solubleSalts": "0.95",
      "phRating": "Medium",
      "organicCarbonRating": "Optimum",
      "nitrogenRating": "Medium",
      "phosphorusRating": "Optimum",
      "potassiumRating": "Optimum"
    }
  ]
}'

