import { prisma } from "./prisma";
import { Role } from "@prisma/client";
import { hashPassword } from "./password";

const sampleRecords = [
  {
    consumerId: "10021",
    name: "Ghulam Hassan Lone",
    parentage: "Abdul Gani Lone",
    address: "Pampore Town",
    district: "Pulwama",
    pinCode: "192121",
    phoneNo: "9876543210",
    adharNo: "452187652341",
    khasraNo: "128/4",
    latitude: "34.0150",
    longitude: "74.9290",
    location: "Pampore Saffron Belt",
    city: "Pampore",
    stateVal: "Jammu & Kashmir",
    crop: "Saffron",
    variety: "Shahi Super",
    plantationType: "Traditional",
    age: 4,
    noTrees: 0,
    area: 5.5,
    noOfSamples: 4,
    soilDepth: "0-15 cm",
    soilType: "Clay Loam",
    drainage: "Well Drained",
    irrigationMethod: "Drip Irrigation",
    paramPh: true,
    paramDl: true,
    paramCl: true,
    parameterPrice: 600,
    paymentStatus: "Paid",
    paidAmount: 600,
    paymentDate: new Date("2026-09-15"),
    createdAt: new Date("2026-09-12"),
    ph: "7.2",
    organicCarbon: "0.85",
    nitrogen: "240",
    phosphorus: "18",
    potassium: "220",
    calcium: "1450",
    magnesium: "320",
    nitrogenRating: "Medium",
    phosphorusRating: "Optimal",
    potassiumRating: "High",
    testResults: [
      {
        id: "tr-1",
        labTestNo: "LAB-2026-091",
        ph: "7.2",
        bufferPh: "7.0",
        organicCarbon: "0.85",
        phRating: "Neutral",
        organicCarbonRating: "Medium",
        nitrogen: "240",
        phosphorus: "18",
        potassium: "220",
        calcium: "1450",
        magnesium: "320",
        sulfur: "14.5",
        zinc: "1.2",
        iron: "4.8",
        copper: "0.9",
        manganese: "3.4",
        boron: "0.6",
        electricalConductivity: "0.32",
        nitrogenRating: "Medium",
        phosphorusRating: "Optimal",
        potassiumRating: "High",
        nitrogenRecommendation: {
          level: "Medium",
          increasePercent: 15,
          suggestion: "Apply urea in split doses during active growth stage.",
        },
        phosphorusRecommendation: {
          level: "Optimal",
          increasePercent: 0,
          suggestion: "Maintain baseline DAP maintenance dosage.",
        },
        potassiumRecommendation: {
          level: "High",
          increasePercent: 0,
          suggestion: "Adequate potash reserves present.",
        },
      },
    ],
  },
  {
    consumerId: "10022",
    name: "Mohammad Altaf Bhat",
    parentage: "Habibullah Bhat",
    address: "Apple Valley, Shopian",
    district: "Shopian",
    pinCode: "192303",
    phoneNo: "9797123456",
    adharNo: "654312879034",
    khasraNo: "44/2",
    latitude: "33.7210",
    longitude: "74.8320",
    location: "Heepora Orchard",
    city: "Shopian",
    stateVal: "Jammu & Kashmir",
    crop: "Apple",
    variety: "Kullu Delicious",
    plantationType: "High Density",
    age: 6,
    noTrees: 650,
    area: 4.2,
    noOfSamples: 3,
    soilDepth: "15-30 cm",
    soilType: "Sandy Loam",
    drainage: "Well Drained",
    irrigationMethod: "Drip Irrigation",
    paramPh: true,
    paramDl: true,
    paramCl: true,
    parameterPrice: 750,
    paymentStatus: "Paid",
    paidAmount: 750,
    paymentDate: new Date("2026-08-20"),
    createdAt: new Date("2026-08-18"),
    ph: "6.4",
    organicCarbon: "1.10",
    nitrogen: "310",
    phosphorus: "24",
    potassium: "280",
    calcium: "1800",
    magnesium: "410",
    nitrogenRating: "Optimal",
    phosphorusRating: "High",
    potassiumRating: "High",
    testResults: [
      {
        id: "tr-2",
        labTestNo: "LAB-2026-082",
        ph: "6.4",
        bufferPh: "6.3",
        organicCarbon: "1.10",
        phRating: "Slightly Acidic",
        organicCarbonRating: "High",
        nitrogen: "310",
        phosphorus: "24",
        potassium: "280",
        calcium: "1800",
        magnesium: "410",
        sulfur: "18.0",
        zinc: "1.8",
        iron: "5.5",
        copper: "1.2",
        manganese: "4.1",
        boron: "0.85",
        electricalConductivity: "0.45",
        nitrogenRating: "Optimal",
        phosphorusRating: "High",
        potassiumRating: "High",
        nitrogenRecommendation: {
          level: "Optimal",
          increasePercent: 0,
          suggestion: "Optimal nitrogen level; continue standard fertigation schedule.",
        },
        phosphorusRecommendation: {
          level: "High",
          increasePercent: 0,
          suggestion: "Slightly reduce superphosphate applications.",
        },
        potassiumRecommendation: {
          level: "High",
          increasePercent: 0,
          suggestion: "Potassium levels are sufficient for fruit color & firmness.",
        },
      },
    ],
  },
  {
    consumerId: "10023",
    name: "Shabir Ahmad Mir",
    parentage: "Mohammad Subhan Mir",
    address: "Pattan Orchard Belt",
    district: "Baramulla",
    pinCode: "193121",
    phoneNo: "9622554433",
    adharNo: "981245672301",
    khasraNo: "88/B",
    latitude: "34.1620",
    longitude: "74.5510",
    location: "Pattan North",
    city: "Pattan",
    stateVal: "Jammu & Kashmir",
    crop: "Apple",
    variety: "Red Delicious",
    plantationType: "Traditional",
    age: 12,
    noTrees: 420,
    area: 6.0,
    noOfSamples: 5,
    soilDepth: "0-15 cm",
    soilType: "Clay Loam",
    drainage: "Moderate",
    irrigationMethod: "Flood Irrigation",
    paramPh: true,
    paramDl: true,
    paramCl: false,
    parameterPrice: 500,
    paymentStatus: "Paid",
    paidAmount: 500,
    paymentDate: new Date("2026-07-14"),
    createdAt: new Date("2026-07-10"),
    ph: "5.8",
    organicCarbon: "0.62",
    nitrogen: "180",
    phosphorus: "12",
    potassium: "160",
    calcium: "1100",
    magnesium: "240",
    nitrogenRating: "Low",
    phosphorusRating: "Low",
    potassiumRating: "Medium",
    testResults: [
      {
        id: "tr-3",
        labTestNo: "LAB-2026-071",
        ph: "5.8",
        bufferPh: "5.6",
        organicCarbon: "0.62",
        phRating: "Moderately Acidic",
        organicCarbonRating: "Low",
        nitrogen: "180",
        phosphorus: "12",
        potassium: "160",
        calcium: "1100",
        magnesium: "240",
        sulfur: "10.2",
        zinc: "0.7",
        iron: "3.2",
        copper: "0.5",
        manganese: "2.1",
        boron: "0.35",
        electricalConductivity: "0.22",
        nitrogenRating: "Low",
        phosphorusRating: "Low",
        potassiumRating: "Medium",
        nitrogenRecommendation: {
          level: "Low",
          increasePercent: 30,
          suggestion: "Apply recommended organic manure (FYM) and boost basal nitrogen.",
        },
        phosphorusRecommendation: {
          level: "Low",
          increasePercent: 25,
          suggestion: "Apply single superphosphate with lime to balance pH.",
        },
        potassiumRecommendation: {
          level: "Medium",
          increasePercent: 15,
          suggestion: "Supplement with Muriate of Potash.",
        },
      },
    ],
  },
  {
    consumerId: "10024",
    name: "Bashir Ahmad Dar",
    parentage: "Abdul Ahad Dar",
    address: "Hajan Nut Estate",
    district: "Bandipora",
    pinCode: "193501",
    phoneNo: "9596112233",
    adharNo: "741258963012",
    khasraNo: "201/A",
    latitude: "34.4210",
    longitude: "74.6420",
    location: "Bandipora Hills",
    city: "Bandipora",
    stateVal: "Jammu & Kashmir",
    crop: "Walnut",
    variety: "Kagzi Premium",
    plantationType: "Traditional",
    age: 20,
    noTrees: 180,
    area: 8.5,
    noOfSamples: 4,
    soilDepth: "30-60 cm",
    soilType: "Silt Loam",
    drainage: "Well Drained",
    irrigationMethod: "Rainfed",
    paramPh: true,
    paramDl: true,
    paramCl: true,
    parameterPrice: 800,
    paymentStatus: "Paid",
    paidAmount: 800,
    paymentDate: new Date("2026-06-25"),
    createdAt: new Date("2026-06-20"),
    ph: "6.8",
    organicCarbon: "0.95",
    nitrogen: "270",
    phosphorus: "21",
    potassium: "245",
    calcium: "1600",
    magnesium: "380",
    nitrogenRating: "Optimal",
    phosphorusRating: "Optimal",
    potassiumRating: "Optimal",
    testResults: [
      {
        id: "tr-4",
        labTestNo: "LAB-2026-064",
        ph: "6.8",
        bufferPh: "6.7",
        organicCarbon: "0.95",
        phRating: "Neutral / Optimal",
        organicCarbonRating: "High",
        nitrogen: "270",
        phosphorus: "21",
        potassium: "245",
        calcium: "1600",
        magnesium: "380",
        sulfur: "16.4",
        zinc: "1.4",
        iron: "5.1",
        copper: "1.0",
        manganese: "3.8",
        boron: "0.72",
        electricalConductivity: "0.38",
        nitrogenRating: "Optimal",
        phosphorusRating: "Optimal",
        potassiumRating: "Optimal",
        nitrogenRecommendation: {
          level: "Optimal",
          increasePercent: 0,
          suggestion: "Nutrient levels are well-balanced for mature walnut canopies.",
        },
        phosphorusRecommendation: {
          level: "Optimal",
          increasePercent: 0,
          suggestion: "Maintain regular annual compost additions.",
        },
        potassiumRecommendation: {
          level: "Optimal",
          increasePercent: 0,
          suggestion: "Healthy potassium index for nut shell development.",
        },
      },
    ],
  },
  {
    consumerId: "10025",
    name: "Farooq Ahmad Rather",
    parentage: "Ghulam Nabi Rather",
    address: "Breng Valley, Kokernag",
    district: "Anantnag",
    pinCode: "192202",
    phoneNo: "9419011223",
    adharNo: "852196374102",
    khasraNo: "55/1",
    latitude: "33.5820",
    longitude: "75.3110",
    location: "Kokernag Orchards",
    city: "Kokernag",
    stateVal: "Jammu & Kashmir",
    crop: "Cherry",
    variety: "Mishri Cherry",
    plantationType: "Semi-Dwarf",
    age: 7,
    noTrees: 340,
    area: 3.8,
    noOfSamples: 3,
    soilDepth: "0-15 cm",
    soilType: "Loamy Sand",
    drainage: "Well Drained",
    irrigationMethod: "Sprinkler",
    paramPh: true,
    paramDl: true,
    paramCl: true,
    parameterPrice: 650,
    paymentStatus: "Pending",
    paidAmount: 0,
    createdAt: new Date("2026-09-22"),
    ph: "6.6",
    organicCarbon: "0.78",
    nitrogen: "220",
    phosphorus: "16",
    potassium: "210",
    calcium: "1350",
    magnesium: "290",
    testResults: [
      {
        id: "tr-5",
        labTestNo: "LAB-2026-095",
        ph: "6.6",
        bufferPh: "6.5",
        organicCarbon: "0.78",
        phRating: "Neutral",
        organicCarbonRating: "Medium",
        nitrogen: "220",
        phosphorus: "16",
        potassium: "210",
        calcium: "1350",
        magnesium: "290",
        sulfur: "12.8",
        zinc: "1.1",
        iron: "4.2",
        copper: "0.8",
        manganese: "3.0",
        boron: "0.55",
        electricalConductivity: "0.28",
        nitrogenRating: "Medium",
        phosphorusRating: "Optimal",
        potassiumRating: "Optimal",
      },
    ],
  },
  {
    consumerId: "10026",
    name: "Tariq Ahmad Shah",
    parentage: "Mohammad Amin Shah",
    address: "Chadoora Plantation",
    district: "Budgam",
    pinCode: "191113",
    phoneNo: "9796001122",
    adharNo: "369258147025",
    khasraNo: "112/3",
    latitude: "33.9510",
    longitude: "74.7890",
    location: "Chadoora Valley",
    city: "Budgam",
    stateVal: "Jammu & Kashmir",
    crop: "Almond",
    variety: "Nonpareil",
    plantationType: "Traditional",
    age: 9,
    noTrees: 260,
    area: 4.5,
    noOfSamples: 2,
    soilDepth: "15-30 cm",
    soilType: "Clay Loam",
    drainage: "Moderate",
    irrigationMethod: "Rainfed",
    paramPh: true,
    paramDl: false,
    paramCl: true,
    parameterPrice: 450,
    paymentStatus: "Paid",
    paidAmount: 450,
    paymentDate: new Date("2026-05-18"),
    createdAt: new Date("2026-05-15"),
    ph: "7.6",
    organicCarbon: "0.55",
    nitrogen: "190",
    phosphorus: "14",
    potassium: "195",
    calcium: "1900",
    magnesium: "450",
    testResults: [
      {
        id: "tr-6",
        labTestNo: "LAB-2026-052",
        ph: "7.6",
        bufferPh: "7.4",
        organicCarbon: "0.55",
        phRating: "Slightly Alkaline",
        organicCarbonRating: "Low",
        nitrogen: "190",
        phosphorus: "14",
        potassium: "195",
        calcium: "1900",
        magnesium: "450",
        sulfur: "11.0",
        zinc: "0.8",
        iron: "3.5",
        copper: "0.6",
        manganese: "2.4",
        boron: "0.48",
        electricalConductivity: "0.35",
      },
    ],
  },
  {
    consumerId: "10027",
    name: "Javaid Iqbal Qadri",
    parentage: "Ghulam Qadir",
    address: "Hazratbal Agro Zone",
    district: "Srinagar",
    pinCode: "190006",
    phoneNo: "9906114455",
    adharNo: "123456789099",
    khasraNo: "77/9",
    latitude: "34.1250",
    longitude: "74.8420",
    location: "Dal Lake Catchment",
    city: "Srinagar",
    stateVal: "Jammu & Kashmir",
    crop: "Vegetables",
    variety: "Exotic Greens",
    plantationType: "High Density",
    age: 1,
    noTrees: 0,
    area: 2.2,
    noOfSamples: 2,
    soilDepth: "0-15 cm",
    soilType: "Silty Clay",
    drainage: "Well Drained",
    irrigationMethod: "Drip Irrigation",
    paramPh: true,
    paramDl: true,
    paramCl: true,
    parameterPrice: 600,
    paymentStatus: "Paid",
    paidAmount: 600,
    paymentDate: new Date("2026-09-01"),
    createdAt: new Date("2026-08-28"),
    ph: "6.9",
    organicCarbon: "1.45",
    nitrogen: "340",
    phosphorus: "28",
    potassium: "310",
    calcium: "2100",
    magnesium: "480",
    testResults: [
      {
        id: "tr-7",
        labTestNo: "LAB-2026-089",
        ph: "6.9",
        bufferPh: "6.8",
        organicCarbon: "1.45",
        phRating: "Optimal Neutral",
        organicCarbonRating: "Very High",
        nitrogen: "340",
        phosphorus: "28",
        potassium: "310",
        calcium: "2100",
        magnesium: "480",
        sulfur: "22.5",
        zinc: "2.3",
        iron: "6.8",
        copper: "1.5",
        manganese: "5.2",
        boron: "1.1",
        electricalConductivity: "0.52",
      },
    ],
  },
  {
    consumerId: "10028",
    name: "Nisar Ahmad Wani",
    parentage: "Abdul Salam Wani",
    address: "Kulgam Apple Zone",
    district: "Kulgam",
    pinCode: "192231",
    phoneNo: "9697445566",
    adharNo: "456123789012",
    khasraNo: "33/4",
    latitude: "33.6450",
    longitude: "75.0120",
    location: "Kulgam Main",
    city: "Kulgam",
    stateVal: "Jammu & Kashmir",
    crop: "Apple",
    variety: "Gala Delicious",
    plantationType: "High Density",
    age: 5,
    noTrees: 520,
    area: 3.5,
    noOfSamples: 3,
    soilDepth: "0-15 cm",
    soilType: "Clay Loam",
    drainage: "Well Drained",
    irrigationMethod: "Drip Irrigation",
    paramPh: true,
    paramDl: true,
    paramCl: false,
    parameterPrice: 550,
    paymentStatus: "Paid",
    paidAmount: 550,
    paymentDate: new Date("2026-04-12"),
    createdAt: new Date("2026-04-10"),
    ph: "6.2",
    organicCarbon: "0.88",
    nitrogen: "260",
    phosphorus: "19",
    potassium: "230",
    calcium: "1500",
    magnesium: "340",
    testResults: [
      {
        id: "tr-8",
        labTestNo: "LAB-2026-041",
        ph: "6.2",
        bufferPh: "6.1",
        organicCarbon: "0.88",
        phRating: "Slightly Acidic",
        organicCarbonRating: "Medium",
        nitrogen: "260",
        phosphorus: "19",
        potassium: "230",
        calcium: "1500",
        magnesium: "340",
        sulfur: "15.0",
        zinc: "1.3",
        iron: "4.6",
        copper: "0.9",
        manganese: "3.5",
        boron: "0.65",
        electricalConductivity: "0.34",
      },
    ],
  },
];

const seed = async () => {
  try {
    console.log("🌱 Starting comprehensive database seeding...");

    // Clear existing users and records for clean seed
    await prisma.user.deleteMany({});
    console.log("🗑️  Cleared existing users");

    await prisma.record.deleteMany({});
    console.log("🗑️  Cleared existing records");

    // Create superAdmin user
    const adminPassword = hashPassword("admin123");
    await prisma.user.create({
      data: {
        email: "admin@example.com",
        password: adminPassword,
        role: Role.superAdmin,
      },
    });
    console.log("✅ Created superAdmin user (email: admin@example.com, password: admin123)");

    // Create admin user
    const testPassword = hashPassword("test123");
    await prisma.user.create({
      data: {
        email: "test@example.com",
        password: testPassword,
        role: Role.admin,
      },
    });
    console.log("✅ Created admin user (email: test@example.com, password: test123)");

    // Create sample records
    console.log("🌾 Creating realistic soil testing records...");
    for (const rec of sampleRecords) {
      await prisma.record.create({
        data: rec as any,
      });
    }
    console.log(`✅ Seeded ${sampleRecords.length} comprehensive soil test records with multi-parameter analytics!`);

    const users = await prisma.user.findMany({
      select: { email: true, role: true },
    });
    console.log(`\n📊 Total Users in DB: ${users.length}`);
    users.forEach((user) => {
      console.log(`  - ${user.email} (${user.role})`);
    });

    const recordCount = await prisma.record.count();
    console.log(`📊 Total Records in DB: ${recordCount}`);

    console.log("\n✨ Seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
};

seed();
